[package]
name = "obex-server"
version = "0.1.0"
authors = ["David Zemon <david@zemon.name>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
